### ISSUE TITLE
🚨 "The remote sync data is incoherent" error on sync between android and windows WebDav

### ISSUE THREAD

**Issue by KHILL3000** [super-productivity/super-productivity#4478]
### Version Used

Windows 13.0.9 Android 13.0.10 L2A

### Expected Behavior

When I click sync the changes I made on the remote machine get pushed over to the machine i'm on

### Current Behavior

I setup a WebDav server using SFTPgo, and I was eventually able to have my windows machine sync to it, but when i go to my android device and try to sync i get a popup saying "sync: conflicting data" "Update from remote. Both local and remote data seem to be modified."

I click "Keep remote" since it has newer stuff and I've already backed up what I had on the android app. Then I get a popup saying 
"The remote sync data is incoherent!
Affected model: issueProvider,[object Object] "   -this has been different

I've deleted everything in the shared folder and had the windows machine back up the files again to make sure nothing was corrupted and I'm still getting the same error. What should I do?

### Steps to Reproduce

1 Setup a WebDav sync 
2 Sync from a Windows Machine
3 Try to sync from an Android

### Can you reproduce this reliably?

Yes, I can reproduce it reliably.

### Console Output

```shell

```

**Comment by KHILL3000** [comment]
Looks like this is being addressed in #4391

**Comment by aenaveen** [comment]
Have the same issue "The remote sync data is incoherent" for pluginUserData, globalConfig.
Trying to sync one platform after syncing on another previously will give this error. 
Seems like it's still not fixed as of 14.2.2

**Comment by johannesjo** [comment]
13.0.9 is a bit outdated. Please try with the latest version.

@aenaveen 

Could it be that you are using different app versions on both devices?

**Comment by johannesjo** [comment]
I believe that this will be fixed with the next version.
